"""Bridge between the strategy engine and the TradingAgents LLM framework.

This is where the two halves of the repo meet. The price-action engine produces
a deterministic, rule-checked verdict; TradingAgents supplies the multi-agent
LLM layer that can argue about it in words.

Two things are deliberate:

* **The engine stays authoritative.** The LLM writes a bull case, a bear case
  and a verdict, but it cannot promote a setup the rules rejected. "No indicator
  tells you the trend" applies to language models too.
* **Nothing is fabricated when the LLM is unavailable.** With no package or no
  API key the bridge says so and returns no review. It never emits
  LLM-sounding prose generated by string templates.

TradingAgents' own ``propagate()`` pipeline is built around equity/crypto data
vendors, so it is not used to fetch FX data. What is reused is its provider
registry, model catalogue and LLM client factory.
"""

from __future__ import annotations

import json
import os
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

#: The TradingAgents package lives at the repository root, one level above
#: ``backend/``. Add it to the path so the bridge works whether the API is
#: started from the repo root or from inside ``backend/``.
_REPO_ROOT = Path(__file__).resolve().parents[3]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))


#: Providers tried, in order, when ``TRADINGAGENTS_LLM_PROVIDER`` is not set:
#: the first one whose API key is present in the environment wins. This is what
#: makes "drop GROQ_API_KEY in .env and restart" enough on its own - without it
#: the provider would stay on the ``default_config`` value (OpenAI) and the
#: status endpoint would ask for the wrong key.
PROVIDER_PREFERENCE: tuple = (
    "groq",
    "openai",
    "anthropic",
    "google",
    "deepseek",
    "openrouter",
    "mistral",
    "nvidia",
    "xai",
)

#: Fallback model per provider, used when ``TRADINGAGENTS_QUICK_THINK_LLM`` is
#: unset. ``default_config``'s model name is an OpenAI one, so it cannot be sent
#: to Groq - the request would 404 on an unknown model. Override with
#: ``TRADINGAGENTS_QUICK_THINK_LLM`` to use any other model your key can reach.
#: The client module each provider needs at call time. ``tradingagents`` itself
#: imports cleanly without these - the LLM SDKs are only pulled in by the client
#: factory - so a bare checkout reports "ready", then fails on the first review
#: with an ImportError. Checking here turns that into an up-front instruction.
CLIENT_MODULES: Dict[str, str] = {
    "anthropic": "langchain_anthropic",
    "google": "langchain_google_genai",
    "bedrock": "langchain_aws",
}

#: Used by every OpenAI-compatible provider, Groq included.
DEFAULT_CLIENT_MODULE: str = "langchain_openai"

DEFAULT_MODELS: Dict[str, str] = {
    "groq": "llama-3.3-70b-versatile",
    "openai": "gpt-5.4-mini",
    "anthropic": "claude-sonnet-5",
    "google": "gemini-2.5-flash",
    "deepseek": "deepseek-chat",
    "mistral": "mistral-large-latest",
}


@dataclass
class BridgeStatus:
    """Whether an LLM second opinion can actually be produced right now."""

    available: bool
    package_importable: bool
    provider: str = ""
    model: str = ""
    api_key_env: Optional[str] = None
    api_key_present: bool = False
    reason: str = ""
    #: True when the provider was picked from the environment rather than set
    #: explicitly - surfaced in the UI so the choice is never a surprise.
    provider_autodetected: bool = False
    #: True when TRADINGAGENTS_LLM_PROVIDER pinned the provider. When false,
    #: dropping in any supported key switches the provider to match it, so the
    #: UI can suggest whichever key the user actually has.
    provider_explicit: bool = False


@dataclass
class SetupReview:
    """An LLM second opinion on a rule-checked setup."""

    available: bool
    symbol: str = ""
    engine_verdict: str = ""
    bull_case: str = ""
    bear_case: str = ""
    verdict: str = ""
    key_risks: List[str] = field(default_factory=list)
    model_used: str = ""
    reason: str = ""
    disclaimer: str = (
        "AI-generated commentary on a rule-based analysis. Informational only, "
        "not financial advice. The strategy engine's verdict is authoritative; "
        "this commentary cannot approve a setup the rules rejected."
    )


SYSTEM_PROMPT = """You are reviewing a forex setup that has ALREADY been \
evaluated by a deterministic price-action engine implementing a specific \
trading strategy (top-down market structure, Areas of Interest, break-and-retest \
entries, candlestick and Head & Shoulders patterns, confluence scoring).

Your job is to argue both sides of the setup and give a verdict.

Hard constraints:
- The engine's rule verdicts are FACTS. Do not dispute whether an AOI is valid, \
whether a trigger armed, or what the trend is - those are computed, not opinions.
- If the engine found the setup ineligible, you MUST NOT recommend taking it. \
Explain what is missing instead.
- Never invent price levels, patterns or news that are not in the brief.
- Be concrete and brief. No hedging filler.

Respond with ONLY a JSON object, no markdown fence:
{"bull_case": "...", "bear_case": "...", "verdict": "...", "key_risks": ["..."]}"""


class TradingAgentsBridge:
    """Runs an LLM review of a strategy-engine analysis, when configured."""

    def __init__(self) -> None:
        self._client: Any = None
        self._client_key: tuple = ()

    # -- availability ----------------------------------------------------

    def status(self) -> BridgeStatus:
        """Report whether a review can be produced, and why not if it cannot."""
        try:
            from tradingagents.default_config import DEFAULT_CONFIG
            from tradingagents.llm_clients.api_key_env import get_api_key_env
        except Exception as exc:
            return BridgeStatus(
                available=False,
                package_importable=False,
                reason=(
                    f"The tradingagents package could not be imported ({exc}). "
                    f"Install the repo root's dependencies: pip install -e ."
                ),
            )

        explicit_provider = os.getenv("TRADINGAGENTS_LLM_PROVIDER", "").strip()
        provider = explicit_provider
        autodetected = False

        if not provider:
            provider = self._detect_provider(get_api_key_env)
            autodetected = provider is not None
            provider = provider or DEFAULT_CONFIG.get("llm_provider", "openai")

        model = self._model_for(provider, DEFAULT_CONFIG)
        key_env = get_api_key_env(provider)
        key_present = bool(key_env is None or os.getenv(key_env, "").strip())

        if not key_present:
            return BridgeStatus(
                available=False,
                package_importable=True,
                provider=provider,
                model=model,
                api_key_env=key_env,
                api_key_present=False,
                provider_autodetected=autodetected,
                provider_explicit=bool(explicit_provider),
                reason=(
                    f"No API key found for provider '{provider}'. Put "
                    f"{key_env}=... in the repo root .env and restart the API."
                    if explicit_provider
                    else (
                        "No API key found for any supported provider. Put one "
                        "key in the repo root .env and restart the API - the "
                        "provider is picked to match it. The strategy engine "
                        "itself needs no key and works without this."
                    )
                ),
            )

        missing = self._missing_client_module(provider)
        if missing:
            return BridgeStatus(
                available=False,
                package_importable=True,
                provider=provider,
                model=model,
                api_key_env=key_env,
                api_key_present=True,
                provider_autodetected=autodetected,
                provider_explicit=bool(explicit_provider),
                reason=(
                    f"{key_env} is set, but the '{provider}' client needs "
                    f"{missing}, which is not installed. Run "
                    f"'pip install -e .' from the repo root. The strategy "
                    f"engine needs none of this and works without it."
                ),
            )

        return BridgeStatus(
            available=True,
            package_importable=True,
            provider=provider,
            model=model,
            api_key_env=key_env,
            api_key_present=True,
            provider_autodetected=autodetected,
            provider_explicit=bool(explicit_provider),
            reason=(
                f"Ready - {provider}/{model}."
                + (
                    f" Provider picked from the environment because "
                    f"{key_env} is set and TRADINGAGENTS_LLM_PROVIDER is not."
                    if autodetected
                    else ""
                )
            ),
        )

    @staticmethod
    def _missing_client_module(provider: str) -> Optional[str]:
        """Name of the import the provider's client needs, if it is absent."""
        import importlib.util

        for module in ("langchain_core", CLIENT_MODULES.get(provider, DEFAULT_CLIENT_MODULE)):
            try:
                found = importlib.util.find_spec(module) is not None
            except (ImportError, ValueError):
                found = False
            if not found:
                return module
        return None

    @staticmethod
    def _detect_provider(get_api_key_env) -> Optional[str]:
        """First provider in ``PROVIDER_PREFERENCE`` whose key is in the env."""
        for candidate in PROVIDER_PREFERENCE:
            env = get_api_key_env(candidate)
            if env and os.getenv(env, "").strip():
                return candidate
        return None

    @staticmethod
    def _model_for(provider: str, default_config: Dict[str, Any]) -> str:
        """Model to call: explicit env first, then a per-provider default.

        ``default_config``'s ``quick_think_llm`` is an OpenAI model name, so it
        is only used when the provider actually is OpenAI - sending it to Groq
        would fail on an unknown model rather than on anything the user did.
        """
        explicit = os.getenv("TRADINGAGENTS_QUICK_THINK_LLM", "").strip()
        if explicit:
            return explicit
        if provider in DEFAULT_MODELS:
            return DEFAULT_MODELS[provider]
        return default_config.get("quick_think_llm", "")

    # -- review ----------------------------------------------------------

    def review(self, analysis: Dict[str, Any]) -> SetupReview:
        """Ask the LLM for a bull/bear review of a rule-checked setup.

        Args:
            analysis: a serialised strategy analysis (``AnalysisOut``).

        Returns:
            A :class:`SetupReview`. ``available`` is false - with a ``reason`` -
            whenever the LLM could not be reached. No prose is invented in that
            case.
        """
        status = self.status()
        engine_verdict = self._engine_verdict(analysis)

        if not status.available:
            return SetupReview(
                available=False,
                symbol=analysis.get("symbol", ""),
                engine_verdict=engine_verdict,
                reason=status.reason,
            )

        try:
            client = self._get_client(status.provider, status.model)
            brief = self._build_brief(analysis)
            raw = client.invoke(
                [
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": brief},
                ]
            )
            content = getattr(raw, "content", raw)
            parsed = self._parse(str(content))
        except Exception as exc:
            return SetupReview(
                available=False,
                symbol=analysis.get("symbol", ""),
                engine_verdict=engine_verdict,
                reason=f"The LLM call failed: {exc}",
            )

        if parsed is None:
            return SetupReview(
                available=False,
                symbol=analysis.get("symbol", ""),
                engine_verdict=engine_verdict,
                reason="The model did not return the expected JSON shape.",
            )

        return SetupReview(
            available=True,
            symbol=analysis.get("symbol", ""),
            engine_verdict=engine_verdict,
            bull_case=parsed.get("bull_case", ""),
            bear_case=parsed.get("bear_case", ""),
            verdict=parsed.get("verdict", ""),
            key_risks=list(parsed.get("key_risks", []) or []),
            model_used=f"{status.provider}/{status.model}",
        )

    # -- internals -------------------------------------------------------

    def _get_client(self, provider: str, model: str):
        """Create (and cache) the LLM client for this provider/model pair."""
        from tradingagents.llm_clients.factory import create_llm_client

        key = (provider, model)
        if self._client is None or self._client_key != key:
            self._client = create_llm_client(provider, model)
            self._client_key = key
        return self._client

    @staticmethod
    def _engine_verdict(analysis: Dict[str, Any]) -> str:
        confluence = analysis.get("confluence") or {}
        if analysis.get("tradeable"):
            return (
                f"ELIGIBLE - all four core pillars passed, confluence "
                f"{confluence.get('score', 0)}/{confluence.get('max_score', 0)}."
            )
        missing = ", ".join(confluence.get("missing_core", [])) or "unknown"
        return f"NOT ELIGIBLE - missing core pillar(s): {missing}."

    @staticmethod
    def _build_brief(analysis: Dict[str, Any]) -> str:
        """Flatten the analysis into a compact factual brief for the model."""
        lines: List[str] = [
            f"PAIR: {analysis.get('symbol')}",
            f"CURRENT PRICE: {analysis.get('current_price')}",
            f"BIAS: {analysis.get('bias')}",
            "",
            "ENGINE NARRATIVE:",
        ]
        lines += [f"  - {line}" for line in analysis.get("narrative", [])]

        top_down = analysis.get("top_down") or {}
        trend_layer = top_down.get("trend_layer") or {}
        lines += ["", "STRUCTURE (trend timeframes):"]
        for tf, structure in trend_layer.items():
            lines.append(f"  - {tf}: {structure.get('summary', structure.get('trend'))}")

        lines += ["", "VALIDATED AOI ZONES:"]
        zones = analysis.get("valid_zones") or []
        if zones:
            for zone in zones[:4]:
                lines.append(
                    f"  - {zone['timeframe']} {zone['golden_rule_tag']} "
                    f"{zone['lower']}-{zone['upper']} "
                    f"({zone['width_pips']} pips, {zone['touches']} touches)"
                )
        else:
            lines.append("  - none")

        trigger = analysis.get("trigger") or {}
        lines += [
            "",
            f"ENTRY TRIGGER: {trigger.get('status', 'none')} at "
            f"{trigger.get('level_label', 'n/a')} ({trigger.get('level', 'n/a')})",
        ]

        patterns = analysis.get("actionable_patterns") or []
        lines += ["", "PATTERNS AT AOI:"]
        lines += (
            [
                f"  - {p['name']} on {p['timeframe']} ({p['bias']}, "
                f"strength {p['weighted_strength']})"
                for p in patterns[:6]
            ]
            or ["  - none"]
        )

        confluence = analysis.get("confluence") or {}
        lines += [
            "",
            f"CORE 4: {json.dumps(confluence.get('core_pillars', {}))}",
            f"EXPANDED SCORE: {confluence.get('score', 0)}/"
            f"{confluence.get('max_score', 0)}",
            f"ENGINE VERDICT: {TradingAgentsBridge._engine_verdict(analysis)}",
        ]

        plan = analysis.get("trade_plan")
        if plan:
            lines += [
                "",
                f"PLAN: {plan['direction']} {plan['position_size_lots']} lots, "
                f"entry {plan['entry']}, stop {plan['stop_loss']}, "
                f"target {plan['take_profit']}, RR 1:{plan['reward_risk']}",
            ]
            if plan.get("warnings"):
                lines += ["PLAN WARNINGS:"] + [
                    f"  - {w}" for w in plan["warnings"]
                ]
        else:
            lines += ["", "PLAN: none - the engine refused to produce one."]

        guardrails = analysis.get("guardrails") or []
        if guardrails:
            lines += ["", "DISCIPLINE MESSAGES:"] + [f"  - {g}" for g in guardrails]

        return "\n".join(lines)

    @staticmethod
    def _parse(content: str) -> Optional[Dict[str, Any]]:
        """Pull the JSON object out of the model's reply."""
        text = content.strip()
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
            text = text.strip()

        try:
            parsed = json.loads(text)
        except json.JSONDecodeError:
            start, end = text.find("{"), text.rfind("}")
            if start == -1 or end <= start:
                return None
            try:
                parsed = json.loads(text[start : end + 1])
            except json.JSONDecodeError:
                return None

        return parsed if isinstance(parsed, dict) else None


#: Process-wide singleton, matching the other services.
tradingagents_bridge = TradingAgentsBridge()
